### ISSUE TITLE
Is changelog maintained?

### ISSUE THREAD

**Issue by okuramasafumi** [line/line-bot-sdk-ruby#117]
I've noticed that the last update of changelog is for `1.2.2`, which is more than a year ago.
I check other SDKs' changelogs and they are maintained well. I think for Ruby SDK the changelog should be maintained.

I hope when the next version comes out, the changelog will be updated as well so that I can close this issue.

**Comment by kimoto** [comment]
Thanks for you report. CHANGELOG file is updated.
https://github.com/line/line-bot-sdk-ruby/blob/master/CHANGELOG.md

**Comment by okuramasafumi** [comment]
@kimoto Thank you, it looks nice!
