### ISSUE TITLE
Support icon-nickname-switch

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-ruby#173]
News: https://developers.line.biz/en/news/2020/03/17/icon-nickname-switch/
Doc: https://developers.line.biz/en/docs/messaging-api/icon-nickname-switch/

**Comment by toduq** [comment]
The current SDK implementation already supports this feature.

```rb
message = {
    type: 'text',
    text: event.message['text'],
    sender: {
        name: 'Cony',
        iconUrl: 'https://line.me/conyprof'
    }
}
client.reply_message(event['replyToken'], message)
```
