### ISSUE TITLE
Support Redelivery object for narrowcast messages

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-ruby#200]
News: https://developers.line.biz/en/news/2020/09/15/messaging-api-narrowcast-requestId/
Docs: [Redelivery object](https://developers.line.biz/en/docs/messaging-api/sending-messages/#redelivery-object)

**Comment by dlackty** [comment]
From my opinion, there's no need to make any change for Ruby SDK here because the API interface takes a free from Hash object and without any type constraints.

**Comment by kimoto** [comment]
Thanks for confirmation. That's right.
