### ISSUE TITLE
Run github actions CI with ruby 3.0

### ISSUE THREAD

**Issue by tokuhirom** [line/line-bot-sdk-ruby#210]
https://github.com/line/line-bot-sdk-ruby/blob/master/.github/workflows/pull_request.yml#L10

ref. https://github.com/actions/setup-ruby/pull/93

**Comment by tokuhirom** [comment]
Maybe we should use https://github.com/ruby/setup-ruby instead.

**Comment by kimoto** [comment]
https://github.com/line/line-bot-sdk-ruby/pull/211
