### ISSUE TITLE
Support follower IDs API

### ISSUE THREAD

**Issue by chocoby** [line/line-bot-sdk-ruby#216]
Thank you for developing and maintaining Ruby SDK!

So, can we add support for get follower IDs API? 

- [Get a list of users who added your LINE Official Account as a friend](https://developers.line.biz/en/reference/messaging-api/#get-follower-ids)

If okay with adding this API, I try to send a Pull Request :)

**Comment by kimoto** [comment]
Thanks for your reporting. It would be great if you could implement it :D

**Comment by chocoby** [comment]
Thank you for release the new version 🎉 
I close this issue.

**Comment by kimoto** [comment]
Thanks! (I reopened it by mistake.)
