### ISSUE TITLE
Incorrect description of types specifier list in Rdoc

### ISSUE THREAD

**Issue by kenta-takeuchi** [line/line-bot-sdk-ruby#257]
https://github.com/line/line-bot-sdk-ruby/blob/147323c29a2b680204f8bf186d82d146ebaff468/lib/line/bot/client.rb#L173

The correct types specifier list is a comma separated in RDoc.
https://www.rubydoc.info/gems/yard/file/docs/Tags.md#types-specifier-list

**Comment by kenta-takeuchi** [comment]
Solved by https://github.com/line/line-bot-sdk-ruby/pull/258

**Comment by zenizh** [comment]
#258 solved this issue.
