### ISSUE TITLE
Delegate the gem's name: "line-bot"

### ISSUE THREAD

**Issue by gogotanaka** [line/line-bot-sdk-ruby#26]
Hi^^
First of all, thank you for implementing such a nice Bot echo systems and having the SDK for Ruby :)

I'm a guy who releases the gem called 'line-bot' through https://rubygems.org. I think it's much better that you guys have this namespace and developers get able to install your gems as 'line-bot'
(* If and only if you guys wish to do this, I'm totally open)

github: https://github.com/aisaac-lab/line-bot
rubygems: https://rubygems.org/gems/line-bot

Thanks!

**Comment by hirohisa** [comment]
Thank you very much for your suggestions, @gogotanaka .
Please give me it's permission.

**Comment by gogotanaka** [comment]
Hi, @hirohisa - san

I've added `hirohisa.kawasaki@gmail.com` to gem: `line-bot`, please feel free to use it in any ways you'd like to do. 

Thanks.

**Comment by hirohisa** [comment]
Thank you, @gogotanaka .

I have confirmed and I try to support with `line-bot`.

Thanks.

**Comment by hirohisa** [comment]
I released version `0.1.7` with `line-bot-api` and `line-bot`.
