### ISSUE TITLE
It seems that no API to retrieve the mid list of the friends of a bot account

### ISSUE THREAD

**Issue by grimmer0125** [line/line-bot-sdk-ruby#27]
Sorry I didn't find a good place to submit this question if it is not suitable to response here. It would be great if Line can add this API for the purpose of broadcasting messages from the Line Bot, otherwise a Line bot needs to remember the mid from each sender. 

I have another question. 
1.Besides using scanning QR-code to add a Line bot account as a friend, is there any other way to add this? Which means does/will a Line bot account have a searchable Line ID?

Thanks.

**Comment by hirohisa** [comment]
Please see the document https://devdocs.line.me/ .
