### ISSUE TITLE
Create chat bot with conversation loop and save message to database

### ISSUE THREAD

**Issue by ttmthanh** [line/line-bot-sdk-ruby#272]
I want to create chat bot with conversation and save message to database.
Example:
Bot: What is your name?
User: ABC
Bot: What is your gender
User: Fale
... etc

Please help me check this problem is it possible?
Thank team for the support

**Comment by kimoto** [comment]
Yes. You can create that bot. But this repository is only supported ruby lang library's issue. It would be better to have the question asked elsewhere.

**Comment by ttmthanh** [comment]
Could you please help me with the relevant libraries? I am also using ruby language. :((
