### ISSUE TITLE
[Question] API returns 423 status with documented request

### ISSUE THREAD

**Issue by caherrerapa** [line/line-bot-sdk-ruby#33]
Hi. I'm trying to call the API from Postman and the request is going through but no matter which value i set for `eventType` is returning status code: 423 (evenType is invalid)

![postman](https://cloud.githubusercontent.com/assets/1084920/17725772/5606b272-6478-11e6-8ea2-e21a3cfb756e.jpg)

@hirohisa are there any changes in the eventType codes that you could share with us? Really appreciate the help

**Comment by hirohisa** [comment]
Sorry, old API is abandoned.
Please new API with the latest SDK (v1.0.0) because response's body are easy to understand about error handling.
