### ISSUE TITLE
I think you have pushed to the wrong gem repository.

### ISSUE THREAD

**Issue by matsubo** [line/line-bot-sdk-ruby#37]
Your code is pushed to 
https://rubygems.org/gems/line-bot

instead of
https://rubygems.org/gems/line-bot-api

**Comment by hirohisa** [comment]
Hi @matsubo .

@gogotanaka  san delegates the gem `line-bot` to us.

FYI:
https://github.com/line/line-bot-sdk-ruby/issues/26

**Comment by matsubo** [comment]
Please update the README and description on rugybems.org.
I'm confused because the API is less compatibility with the previous version.
