### ISSUE TITLE
Example code is wrong on API Reference

### ISSUE THREAD

**Issue by tyfkda** [line/line-bot-sdk-ruby#40]
I tried to use Get Profile API according to Reference (<https://devdocs.line.me/en/?ruby#bot-api-get-profile>):

```rb
response = client.get_profile("<userId>")
if response.code == 200 {  # <= here
  ...
}
```

, but it failed even if `userId` is valid.

I find that `Net::HTTPResponse#code` is `string`, not `integer`: <https://docs.ruby-lang.org/en/2.0.0/Net/HTTPResponse.html>

The code should be:

```rb
response = client.get_profile("<userId>")
if Net::HTTPSuccess === response  # <= Fix.
  ...
end
```

Same fix should be applied to [Get content](https://devdocs.line.me/en/?ruby#get-content) API.

Also, Ruby's `if` syntax is

```rb
if condition [then]
  ...
else
  ...
end
```

, not

```rb
if condition {
  ...
} else {
  ...
}
```

**Comment by hirohisa** [comment]
Thank you for this issue. I will modify documents.

**Comment by hirohisa** [comment]
Fix. Please look at documents: https://devdocs.line.me/en/?ruby#bot-api-get-profile.

**Comment by tyfkda** [comment]
@hirohisa Thank you for the update.

But in the Ruby, `===` operator is not commutative.
`response === Net::HTTPSuccess` is not equal to `Net::HTTPSuccess === response`,
and former one returns `false` even if API access is succeeded.

Would you please fix the code to use `Net::HTTPSuccess === response`, or `case`~`when`, or `kind_of?`? Thanks!

ref: http://stackoverflow.com/a/22949977/6667631
