### ISSUE TITLE
Issue with Push Message API

### ISSUE THREAD

**Issue by caphun** [line/line-bot-sdk-ruby#43]
I setup a LINE Message API account with API access, i.e. I have my "Channel Access Token" already.

When I try the examples in the documentation I get an error message:

In Ruby: (https://devdocs.line.me/en/?ruby#push-message)
```
message = {
  type: 'text',
  text: 'hello'
}
client = Line::Bot::Client.new { |config|
    config.channel_secret = "<channel secret>"
    config.channel_token = "<channel access token>"
}
response = client.push_message("<to>", message)
p response
```
Response `#<Net::HTTPBadRequest 400 Bad Request readbody=true>`

In Shell: (https://devdocs.line.me/en/?shell#push-message)
```
curl -X POST \
-H 'Content-Type:application/json' \
-H 'Authorization: Bearer {ENTER_ACCESS_TOKEN}' \
-d '{
    "to": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "messages":[
        {
            "type":"text",
            "text":"Hello, world1"
        },
        {
            "type":"text",
            "text":"Hello, world2"
        }
    ]
}' https://api.line.me/v2/bot/message/push
```
Response `{"message":"The property, 'to', in the request body is invalid (line: -, column: -)"}`

For the `to` field I used the `mid` obtained from LINE Login.

Please help!

**Comment by be-hase** [comment]
Hi, @caphun 

Maybe, your BOT account does not have PUSH_MESSAGE permission.
Please confirm this permission.

![](https://cloud.githubusercontent.com/assets/903482/20599083/ae4b45dc-b28f-11e6-90c6-0ca5649dba2e.png)

**Comment by be-hase** [comment]
Oh... sorry, I was wrong.

Did you use mid obtained from LINE Login?
Sorry for being confusing. Mid and userId are different things.
Please use userId/groupId/roomId in webhook's response.

**Comment by caphun** [comment]
@be-hase Yes, I used the `mid` from LINE Login. So I can only get the correct `userId` once a user adds the BOT as a friend? As it comes back through a Webhook, is it possible correlate the correct `userId` with the LINE logged in user?

**Comment by be-hase** [comment]
@caphun 
Yes. Currently mid and userId can not be associated. However, we plan to be able to get userId from LINE login soon. We apologize for the inconvenience but please wait for a while.

**Comment by pai911** [comment]
Hi @be-hase Can I ask how can I get push message permission ?

I cannot find the instructions telling us how to open the permission

Thank you!

**Comment by be-hase** [comment]
Hi, @pai911 
Push message permission is allowed to developer trial plan or pay plan.
https://business.line.me/services/bot

**Comment by pai911** [comment]
@be-hase Thanks for the info : )

**Comment by hirohisa** [comment]
I look this issue already resolved.  I close it.

Thank you for your support, @be-hase .

**Comment by dwiyanr** [comment]
> Yes. Currently mid and userId can not be associated. However, we plan to be able to get userId from LINE login soon. We apologize for the inconvenience but please wait for a while.

Is there any info regarding this now?

**Comment by mrmaakun** [comment]
Hi @dwiyanr 

This FAQ entry on our developer site that discusses associating userid and mid may be helpful:

https://developers.line.me/faq#anc6-3

**Comment by ahmath27** [comment]
> Yes. Currently mid and userId can not be associated. However, we plan to be able to get userId from LINE login soon. We apologize for the inconvenience but please wait for a while.
>
@Be-Hase, any update about this?

**Comment by GuitarSucks** [comment]
Please check the comment from mrmaakun and getting userid with LINE login has been already released
Regards

**Comment by JTimings** [comment]
What about account linking similar to Messenger => https://developers.facebook.com/docs/messenger-platform/identity/account-linking/

We have an existing database of customers and want to auth them from within our Line bot so we can use their account data to provide a more relevant experience - is this possible?

**Comment by codenoid** [comment]
how about this @be-hase ? https://github.com/line/line-bot-faq/issues/32

**Comment by herobacklinks** [comment]
NICE SITE

**Comment by simplysolved749** [comment]
hey everyone the great oportunity for everyone to learn to hack[url=https://learn-to-hack.com/]WhatsApp account[/url]for free. learn to hack WhatsApp account of anyone in just few steps its all free of cost..for more info please visit our site 
https://learn-to-hack.com/

**Comment by simplysolved749** [comment]
hey everyone the great oportunity for everyone to learn to [hack WhatsApp](https://learn-to-hack.com/) account for free. learn to hack WhatsApp account of anyone in just few steps its all free of cost..for more info please visit our site 
https://learn-to-hack.com/

**Comment by dilawar14es** [comment]
Are you looking for shops of carpet suppliers in Dubai with low prices? First, let’s have some introduction to carpets in Dubai. Well,
the carpets are the hard surface textiles that have used to cover the floors in the past.For More Visit Our Site
[carpet supplier](https://halafurniture.com/carpets/)

**Comment by usama255** [comment]
Earning money has typically been associated with and restricted to traditional 'offline' route. With the Internet taking over a large part of our lives, more people are looking to ways to earn money online to increase their financial inflows, with secondary income streams.

You should be mindful of the platform that you opt for. While there are numerous ways to earn money online, some of these might be fake. Also, do not expect to earn a huge amount quickly when using online avenues to earn money[.Blogging Hub](
https://waystomakemoneyonlineguide.com/blogging/)

**Comment by usama255** [comment]
Shaheen advertising is leading Dubai based printing company that offers it's customer all printing and advertising  solutions under one proof.[Business cards printing](https://www.shaheenad.com/)
