### ISSUE TITLE
Suggestion: image message objects

### ISSUE THREAD

**Issue by janklimo** [line/line-bot-sdk-ruby#44]
From my testing, it appears image message objects need both `originalContentUrl` and `previewImageUrl `. When I don't include the `previewImageUrl`, no message is sent and no error is returned. We could:

- clearly state they are both required in the docs
- return an error from the server rather than failing silently if required params are missing

**Comment by hirohisa** [comment]
Hi, @janklimo.
I try to send a message excluding `previewImageUrl`:
```
message = {
  type: 'image',
  originalContentUrl: 'https://example.com/image/1'
}
response = client.reply_message(event['replyToken'], message)
```

I got the message from message api server:
```
{"message":"The request body has 1 error(s)","details":[{"message":"May not be empty","property":"messages[0].previewImageUrl"}]}
```

Please check response.body.

FYI: https://devdocs.line.me/ja/?ruby#reply-message

**Comment by janklimo** [comment]
Ah, my bad. Thank you for clarifying that! It would be nice to mention which params are optional and which ones are required [in the docs](https://devdocs.line.me/en/?ruby#send-message-object).

@hirohisa btw great job rewriting this API into its current form 👍  I must say it's a very nice change since the last time I was working with it (version `0.1.6` around 6 months ago) 👏
