### ISSUE TITLE
Need method for get the current user profile

### ISSUE THREAD

**Issue by PeaceS** [line/line-bot-sdk-ruby#52]
ref: https://devdocs.line.me/en/?ruby#getting-user-profiles

the default endpoint is `"https://api.line.me/v2/bot"`, but this api need no `bot` thought

**Comment by hirohisa** [comment]
Thank you for the issue. I changed default endpoint.
try it with version `1.2.1`: 
```
client.get('/profile')
```

**Comment by PeaceS** [comment]
wow, didn't expect these speed, big thanks to you @hirohisa

**Comment by scomma** [comment]
Hi @hirohisa, this endpoint is no longer working, it returns 401 unauthorized. Could you check please?
