### ISSUE TITLE
Update HTTPClient

### ISSUE THREAD

**Issue by hirohisa** [line/line-bot-sdk-ruby#58]
`get(url, header = {})` -> `get(url, parameters, header = {})`

**Comment by tokuhirom** [comment]
What is this mean? @hirohisa san

**Comment by hirohisa** [comment]
It means:

It would be better that using HTTP Client

As-Is:
```
endpoint_path  = "/bot/room/#{room_id}/members/ids"
endpoint_path += "?start=#{continuation_token}" if continuation_token
get(endpoint_path)
```

To-Be:
```
endpoint_path  = "/bot/room/#{room_id}/members/ids"
parameters = {start: continuation_token} if continuation_token
get(endpoint_path, parameters)
```

https://github.com/line/line-bot-sdk-ruby/blob/master/lib/line/bot/client.rb#L219-L223

**Comment by tokuhirom** [comment]
Ah, I see. Hirohisa san said the passing query parameters in a map is better than building query parameters in a string operation.

@toduq @kimoto what do you think about this? if you are agreed to Hirohisa san's opinion, please submit a pull request. otherwise, please close this issue.

**Comment by kimoto** [comment]
This is good idea. But no backward compatibility.
`major version upgrade` or `create new method`
