### ISSUE TITLE
Add API for RichMenu Control

### ISSUE THREAD

**Issue by tokuhirom** [line/line-bot-sdk-ruby#61]
https://developers.line.me/ja/docs/messaging-api/reference/#anchor-57f9aab9ecb405dc744429ef4919d4b7b8de6471

**Comment by jk195417** [comment]
Is there any progress on this #68 ? looking forward to it.

**Comment by kimoto** [comment]
Released 1.2.3 https://github.com/line/line-bot-sdk-ruby/pull/68
