### ISSUE TITLE
NoMethodError raised on Line::Bot::Event:Message

### ISSUE THREAD

**Issue by wisn** [line/line-bot-sdk-ruby#94]
My bot actually works but on the Sinatra logging info there is an exception raised. Although my bot works by replying the message, I always retrieve `500` response code in the logging.

```
[2018-12-14 18:17:00] ERROR NoMethodError: undefined method `bytesize' for #<Line::Bot::Event::Message:0x000055f01290e568>
...
[14/Dec/2018:18:16:59 UTC] "POST /callback HTTP/1.1" 500 396
```

It seems the problem is within `line-bot-sdk-ruby`. Could you fix this?

Ruby used: v2.5.3
Sinatra used: v2.0.4
LINE bot SDK (line-bot-api) used: v1.3.0

**Comment by nyanhacker** [comment]
Same, after using Sinatra with Puma, I get this error :(

**Comment by wisn** [comment]
Try to use Ruby on Rails, I don't get any of this errors. I wonder why.

**Comment by kimoto** [comment]
Did you know this sinatra problem?
```
Sinatra is expecting a string be returned (i.e. last line) of the route method; you can't just return a straight hash.
```
https://stackoverflow.com/questions/16967676/sinatra-undefined-method-bytesize-for-hash/17009205

**Comment by nyanhacker** [comment]
Yeah, It's Works! Very Thanks @wisn & @kimoto

**Comment by toduq** [comment]
This sinatra's behavior is now explicitly documented on the `README.md`.
https://github.com/line/line-bot-sdk-ruby/pull/134

**Comment by wisn** [comment]
Thanks @toduq
