### ISSUE TITLE
rich menu is not supported

### ISSUE THREAD

**Issue by 4geru** [line/line-bot-sdk-ruby#95]
ruby is not supported rich menu apis.
https://developers.line.biz/en/reference/messaging-api/#anchor-1e57ec8125584a6f34a80d7aa6ee4ad5972c0094

**Comment by 4geru** [comment]
it seems supported. but it is not written in document.
https://github.com/line/line-bot-sdk-ruby/blob/107f361fb96334013a91226d3ae6c731f52dfb29/lib/line/bot/client.rb#L231

**Comment by kimoto** [comment]
I will update developer center's document.
Thank you for your report.

**Comment by kimoto** [comment]
@4geru I updated developer doc. Thank for you report.

**Comment by 4geru** [comment]
thank you for your support :)
